# Site settings
title: Escribanas.uy
description: "Escribanas en Rosario, Colonia."
baseurl: "/escriuy" # the subpath of your site, e.g. /blog
url: "www.escribanas.uy" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Escribanas.uy
    hero_description: Tu solución en escribanía

# Contact form
api_token:

# Contact info
contact:
    Teléfono: 
    Email: agaraturra@gmail.com
    Dirección: 

# Opening hours
Lunes a viernes: 09:00 a 12:00 hs.

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 16
    address: Ituzaingo 541, 70200 Rosario, Departamento de Colonia
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: no

# Footer
copyright: © 2018 Escribanas.uy

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
