# Site settings
title: Escribanas.uy
description: "Escribanas en Rosario, Colonia."
baseurl: "/escriuy" # the subpath of your site, e.g. /blog
url: "www.escribanas.uy" # the name of your domain
logo_url: svg/min/logo_H.svg

# Hero
hero: 
    hero_img: gallery/escri2.jpeg
    hero_title: Escribanas.uy
    hero_description: Tu solución en escribanía

# Contact form
api_token:

# Contact info
contact:
    phone: 4552 2317
    email: agaraturra@gmail.com
    address1: Ituzaingó 541 esq. Cerrito
    address2: Rosario, Colonia

# Social settings
feed: no

# Footer
copyright: © 2018 Escribanas.uy

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
